// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKiXD49G5sWCmn6nUMlhNavy05vXZFegw',
    appId: '1:1090027455248:web:e119fec5f2d1aacdc41b95',
    messagingSenderId: '1090027455248',
    projectId: 'workshop2-project-001',
    authDomain: 'workshop2-project-001.firebaseapp.com',
    storageBucket: 'workshop2-project-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_TBrcXw_MlM3uU41imcbIhmi8SVzM4I',
    appId: '1:1090027455248:android:4170896f5bbcc539c41b95',
    messagingSenderId: '1090027455248',
    projectId: 'workshop2-project-001',
    storageBucket: 'workshop2-project-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgNv6C_bimC2_jFr0_nuyeAMznUhrukO0',
    appId: '1:1090027455248:ios:f5c6cebeea7a6db7c41b95',
    messagingSenderId: '1090027455248',
    projectId: 'workshop2-project-001',
    storageBucket: 'workshop2-project-001.firebasestorage.app',
    iosBundleId: 'com.example.inventryx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgNv6C_bimC2_jFr0_nuyeAMznUhrukO0',
    appId: '1:1090027455248:ios:f5c6cebeea7a6db7c41b95',
    messagingSenderId: '1090027455248',
    projectId: 'workshop2-project-001',
    storageBucket: 'workshop2-project-001.firebasestorage.app',
    iosBundleId: 'com.example.inventryx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKiXD49G5sWCmn6nUMlhNavy05vXZFegw',
    appId: '1:1090027455248:web:48ca1b23059e6f45c41b95',
    messagingSenderId: '1090027455248',
    projectId: 'workshop2-project-001',
    authDomain: 'workshop2-project-001.firebaseapp.com',
    storageBucket: 'workshop2-project-001.firebasestorage.app',
  );
}
